---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

```


```{r}
data("rest_inspec")
```

```{r}
rest_inspec = 
  rest_inspec |> 
  select(camis, borough = boro, 
         cuisine_description, score, grade) |> 
  drop_na(score) |>
  filter(borough != 'Missing')
```


Column {data-width=650}
-----------------------------------------------------------------------

### Pie Plot of Top 6 Cuisines of Restaurants in NYC


```{r}
rest_inspec |>
  group_by(cuisine_description) |>
  summarise(restaurant_number = length(cuisine_description)) |>
  arrange(desc(restaurant_number)) |>
  head(6) |>
  plot_ly(
    labels = ~cuisine_description, values = ~restaurant_number) |>
  add_pie(hole = 0.5) |>
  layout(
    legend = list(x = 1, y = 0.5)
  ) 
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar Plot of Restaurants in Each Borough

```{r}
rest_inspec |>
  group_by(borough) |>
  summarise(restaurant_number = length(borough)) |>
  mutate(borough = fct_reorder(borough, restaurant_number)) |> 
  plot_ly(
    x = ~borough, y = ~restaurant_number, color = ~borough,
    type = "bar", colors = "viridis")
```

### Box Plot of Score by Borough

```{r}
rest_inspec |>
  plot_ly(y = ~score, color = ~borough, type = "box", colors = "viridis")
```

