---
title: "Lu Qiu"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: readable
---

### EDUCATION

**Columbia University Mailman School of Public Health** <br>
Master of Biostatistics (MS) <br>
Track: Public Health Data Science <br>
Relevant Courses: Probability, Data Science, Biostatistical Methods, Principles of Epidemiology

**South China University of Technology** <br>
Bachelor of Biomedical Engineering <br>
GPA: 3.69/4.0 (Ranking: 10/69) <br>
Relevant Courses: Calculus, Linear Algebra, Probability & Mathematical Statistics, Python Programming

### SKILLS

**Programming**: R (tidyverse, ggplot2, Shiny), Python (Pandas, NumPy, Matplotlib), SAS, SQL <br>
**Tools**: R Studio, Jupyter Notebook, GitHub, Microsoft Office (Excel, Word, and PowerPoint) <br> 
**Language**: English, Mandarin, Japanese

### CERTIFICATES
Course Certificate on Coursera: Getting Started with SAS Programming [link](https://coursera.org/share/5e3a33e50101a31076375c4a125a6ad4) <br>
Course Certificate on Coursera: R programming [link](https://coursera.org/share/a2517a50f07f235cd1607953afff3e02)<br> 
Course Certificate on Coursera: The Data Scientist’s Toolbox
[link](https://coursera.org/share/b8c48e29daaf28a3bbab032fefad70a9)<br>

### EXPERIENCE
**Abbott, Department of Market Access** <br>
Data Analyst Intern 

* Assisted in the maintenance and update of information on centralized drug procurement platforms in various provinces and cities to ensure that cooperative hospitals can purchase Abbott’s drugs and reagents
* Conducted comprehensive data organization and analysis, utilizing advanced Excel functionalities to process product information and transaction data
* Generated data analysis reports and effectively communicated the results to senior leadership

**Lady Davis Institute for Medical Research, Jewish General Hospital**  <br>
Mitacs Globalink Research Intern 

* Screened articles for eligibility and performed data extraction from eligible studies as part of the systematic review process on DistillerSR (systematic review software)
* Conducted individual participant data meta-analysis (IPDMA) in R, estimating pooled prevalence of depression using generalized linear mixed-effects models (GLMMs)
* Contributed to drafting manuscripts, preparing graphs, tables, supplemental materials, and references for publication (paper in progress)

**iCarbonX, Department of Bioinformatics** <br>
Bioinformatics Intern 

* Analyzed patient data in R using statistical methods, including t-test, Spearman’s correlation, and percentage bend correlation
* Performed data visualization with heatmaps, scatter plots, Venn diagrams, and volcano plots
* Presented results to senior leadership

**School of Mathematics, South China University of Technology** <br>
Project Member    

* Built data pipeline to process COVID-19 data via R, including cleaning, analyzing, and visualizing data using R packages (dplyr, tidyverse, ggplot2, leaflet)           
* Developed an interactive dashboard to show global COVID-19 cases and death distribution using R Shiny
* Built decks and presented results to the team


### HONORS & AWARDS
South China University of Technology Scholarship <br>
COMAP'S Mathematical Contest in Modeling (MCM) - Honorable Mention <br>

### VOLUNTEER EXPERIENCE
Otakuthon Anime Convention <br>
Volunteer

* Assisted crowd control regarding registration matters and offered support to the registration staff
* Monitored the screening room and performed crowd control when a screening room became too crowded
* Helped with sales at the Otakuthon official merchandise table, kept sales inventories, and answered customers'questions

